# Generated by Django 4.1.5 on 2025-08-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/.2025-08-15.11-25-49'),
        ),
    ]
